"use client";

import { useTranslations } from "next-intl";
import Container from "@/components/ui/Container";
import ReportLibrary from "@/components/ReportLibrary";
import { FileText, Sparkles } from "lucide-react";
import { motion } from "framer-motion";

export default function ReportsPage() {
    const t = useTranslations("Navigation");

    return (
        <main className="min-h-screen pt-32 pb-20">
            <Container>
                <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8 mb-12">
                    <div className="space-y-4">
                        <motion.div
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="flex items-center gap-3 mb-4"
                        >
                            <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center">
                                <FileText className="w-6 h-6 text-blue-400" />
                            </div>
                            <h1 className="text-4xl lg:text-5xl font-bold text-white tracking-tight">
                                {t("periodic_reports")}
                            </h1>
                        </motion.div>
                        <motion.p
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.1 }}
                            className="text-slate-400 text-lg max-w-2xl"
                        >
                            Access and download detailed media intelligence reports generated by our Strategic Advisor engine.
                        </motion.p>
                    </div>

                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.2 }}
                        className="bg-slate-900 border border-slate-800 p-6 rounded-3xl lg:max-w-xs w-full"
                    >
                        <div className="flex items-center gap-2 text-blue-400 mb-2">
                            <Sparkles className="w-4 h-4" />
                            <span className="text-[10px] font-bold uppercase tracking-widest">Auto-Generation</span>
                        </div>
                        <p className="text-white font-bold text-sm mb-1">Weekly Digest Ready</p>
                        <p className="text-slate-500 text-[11px] leading-relaxed">
                            Your AI-curated summary for the retail sector is available now.
                        </p>
                    </motion.div>
                </div>

                <div className="space-y-12">
                    <section>
                        <h2 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                            <span className="w-1 h-5 bg-blue-500 rounded-full"></span>
                            Generated Archive
                        </h2>
                        <ReportLibrary />
                    </section>
                </div>
            </Container>
        </main>
    );
}
