export const ALL_COUNTRIES = [
    { code: 'AE', flag: '🇦🇪', en: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة' },
    { code: 'SA', flag: '🇸🇦', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    { code: 'EG', flag: '🇪🇬', en: 'Egypt', ar: 'مصر' },
    { code: 'KW', flag: '🇰🇼', en: 'Kuwait', ar: 'الكويت' },
    { code: 'QA', flag: '🇶🇦', en: 'Qatar', ar: 'قطر' },
    { code: 'BH', flag: '🇧🇭', en: 'Bahrain', ar: 'البحرين' },
    { code: 'OM', flag: '🇴🇲', en: 'Oman', ar: 'عُمان' },
    { code: 'JO', flag: '🇯🇴', en: 'Jordan', ar: 'الأردن' },
    { code: 'LB', flag: '🇱🇧', en: 'Lebanon', ar: 'لبنان' },
    { code: 'IQ', flag: '🇮🇶', en: 'Iraq', ar: 'العراق' },
    { code: 'SY', flag: '🇸🇾', en: 'Syria', ar: 'سوريا' },
    { code: 'PS', flag: '🇵🇸', en: 'Palestine', ar: 'فلسطين' },
    { code: 'YE', flag: '🇾🇪', en: 'Yemen', ar: 'اليمن' },
    { code: 'LY', flag: '🇱🇾', en: 'Libya', ar: 'ليبيا' },
    { code: 'TN', flag: '🇹🇳', en: 'Tunisia', ar: 'تونس' },
    { code: 'DZ', flag: '🇩🇿', en: 'Algeria', ar: 'الجزائر' },
    { code: 'MA', flag: '🇲🇦', en: 'Morocco', ar: 'المغرب' },
    { code: 'SD', flag: '🇸🇩', en: 'Sudan', ar: 'السودان' },
    { code: 'SO', flag: '🇸🇴', en: 'Somalia', ar: 'الصومال' },
    { code: 'DJ', flag: '🇩🇯', en: 'Djibouti', ar: 'جيبوتي' },
    { code: 'MR', flag: '🇲🇷', en: 'Mauritania', ar: 'موريتانيا' },
    { code: 'KM', flag: '🇰🇲', en: 'Comoros', ar: 'جزر القمر' },
    { code: 'US', flag: '🇺🇸', en: 'United States', ar: 'الولايات المتحدة' },
    { code: 'GB', flag: '🇬🇧', en: 'United Kingdom', ar: 'المملكة المتحدة' },
    { code: 'CA', flag: '🇨🇦', en: 'Canada', ar: 'كندا' },
    { code: 'AU', flag: '🇦🇺', en: 'Australia', ar: 'أستراليا' },
    { code: 'FR', flag: '🇫🇷', en: 'France', ar: 'فرنسا' },
    { code: 'DE', flag: '🇩🇪', en: 'Germany', ar: 'ألمانيا' },
    { code: 'IT', flag: '🇮🇹', en: 'Italy', ar: 'إيطاليا' },
    { code: 'ES', flag: '🇪🇸', en: 'Spain', ar: 'إسبانيا' },
    { code: 'NL', flag: '🇳🇱', en: 'Netherlands', ar: 'هولندا' },
    { code: 'BE', flag: '🇧🇪', en: 'Belgium', ar: 'بلجيكا' },
    { code: 'CH', flag: '🇨🇭', en: 'Switzerland', ar: 'سويسرا' },
    { code: 'AT', flag: '🇦🇹', en: 'Austria', ar: 'النمسا' },
    { code: 'SE', flag: '🇸🇪', en: 'Sweden', ar: 'السويد' },
    { code: 'NO', flag: '🇳🇴', en: 'Norway', ar: 'النرويج' },
    { code: 'DK', flag: '🇩🇰', en: 'Denmark', ar: 'الدنمارك' },
    { code: 'FI', flag: '🇫🇮', en: 'Finland', ar: 'فنلندا' },
    { code: 'PL', flag: '🇵🇱', en: 'Poland', ar: 'بولندا' },
    { code: 'PT', flag: '🇵🇹', en: 'Portugal', ar: 'البرتغال' },
    { code: 'GR', flag: '🇬🇷', en: 'Greece', ar: 'اليونان' },
    { code: 'IE', flag: '🇮🇪', en: 'Ireland', ar: 'أيرلندا' },
    { code: 'CZ', flag: '🇨🇿', en: 'Czech Republic', ar: 'التشيك' },
    { code: 'RO', flag: '🇷🇴', en: 'Romania', ar: 'رومانيا' },
    { code: 'HU', flag: '🇭🇺', en: 'Hungary', ar: 'المجر' },
    { code: 'RU', flag: '🇷🇺', en: 'Russia', ar: 'روسيا' },
    { code: 'TR', flag: '🇹🇷', en: 'تركيا', ar: 'تركيا' },
    { code: 'CN', flag: '🇨🇳', en: 'China', ar: 'الصين' },
    { code: 'JP', flag: '🇯🇵', en: 'Japan', ar: 'اليابان' },
    { code: 'KR', flag: '🇰🇷', en: 'South Korea', ar: 'كوريا الجنوبية' },
    { code: 'IN', flag: '🇮🇳', en: 'India', ar: 'الهند' },
    { code: 'PK', flag: '🇵🇰', en: 'Pakistan', ar: 'باكستان' },
    { code: 'BD', flag: '🇧🇩', en: 'Bangladesh', ar: 'بنغلاديش' },
    { code: 'ID', flag: '🇮🇩', en: 'Indonesia', ar: 'إندونيسيا' },
    { code: 'MY', flag: '🇲🇾', en: 'Malaysia', ar: 'ماليزيا' },
    { code: 'SG', flag: '🇸🇬', en: 'Singapore', ar: 'سنغافورة' },
    { code: 'TH', flag: '🇹🇭', en: 'Thailand', ar: 'تايلاند' },
    { code: 'PH', flag: '🇵🇭', en: 'Philippines', ar: 'الفلبين' },
    { code: 'VN', flag: '🇻🇳', en: 'Vietnam', ar: 'فيتنام' },
    { code: 'BR', flag: '🇧🇷', en: 'Brazil', ar: 'البرازيل' },
    { code: 'MX', flag: '🇲🇽', en: 'Mexico', ar: 'المكسيك' },
    { code: 'AR', flag: '🇦🇷', en: 'Argentina', ar: 'الأرجنتين' },
    { code: 'CO', flag: '🇨🇴', en: 'Colombia', ar: 'كولومبيا' },
    { code: 'CL', flag: '🇨🇱', en: 'Chile', ar: 'تشيلي' },
    { code: 'ZA', flag: '🇿🇦', en: 'South Africa', ar: 'جنوب أفريقيا' },
    { code: 'NG', flag: '🇳🇬', en: 'Nigeria', ar: 'نيجيريا' },
    { code: 'KE', flag: '🇰🇪', en: 'Kenya', ar: 'كينيا' },
    { code: 'GH', flag: '🇬🇭', en: 'Ghana', ar: 'غانا' },
    { code: 'ET', flag: '🇪🇹', en: 'Ethiopia', ar: 'إثيوبيا' },
    { code: 'TZ', flag: '🇹🇿', en: 'Tanzania', ar: 'تنزانيا' },
    { code: 'IL', flag: '🇮🇱', en: 'Israel', ar: 'إسرائيل' },
    { code: 'IR', flag: '🇮🇷', en: 'Iran', ar: 'إيران' },
    { code: 'AF', flag: '🇦🇫', en: 'Afghanistan', ar: 'أفغانستان' },
    { code: 'NZ', flag: '🇳🇿', en: 'New Zealand', ar: 'نيوزيلندا' },
    { code: 'UA', flag: '🇺🇦', en: 'Ukraine', ar: 'أوكرانيا' },
    { code: 'HR', flag: '🇭🇷', en: 'Croatia', ar: 'كرواتيا' },
    { code: 'RS', flag: '🇷🇸', en: 'Serbia', ar: 'صربيا' },
    { code: 'BG', flag: '🇧🇬', en: 'Bulgaria', ar: 'بلغاريا' },
    { code: 'SK', flag: '🇸🇰', en: 'Slovakia', ar: 'سلوفاكيا' },
    { code: 'LT', flag: '🇱🇹', en: 'Lithuania', ar: 'ليتوانيا' },
    { code: 'LV', flag: '🇱🇻', en: 'Latvia', ar: 'لاتفيا' },
    { code: 'EE', flag: '🇪🇪', en: 'Estonia', ar: 'إستونيا' },
    { code: 'CY', flag: '🇨🇾', en: 'Cyprus', ar: 'قبرص' },
    { code: 'MT', flag: '🇲🇹', en: 'Malta', ar: 'مالطا' },
    { code: 'LU', flag: '🇱🇺', en: 'Luxembourg', ar: 'لوكسمبورغ' },
    { code: 'IS', flag: '🇮🇸', en: 'Iceland', ar: 'آيسلندا' },
    { code: 'PE', flag: '🇵🇪', en: 'Peru', ar: 'بيرو' },
    { code: 'VE', flag: '🇻🇪', en: 'Venezuela', ar: 'فنزويلا' },
    { code: 'EC', flag: '🇪🇨', en: 'Ecuador', ar: 'الإكوادور' },
    { code: 'UY', flag: '🇺🇾', en: 'Uruguay', ar: 'أوروغواي' },
    { code: 'PY', flag: '🇵🇾', en: 'Paraguay', ar: 'باراغواي' },
    { code: 'BO', flag: '🇧🇴', en: 'Bolivia', ar: 'بوليفيا' },
    { code: 'CR', flag: '🇨🇷', en: 'Costa Rica', ar: 'كوستاريكا' },
    { code: 'PA', flag: '🇵🇦', en: 'Panama', ar: 'بنما' },
    { code: 'CU', flag: '🇨🇺', en: 'Cuba', ar: 'كوبا' },
    { code: 'DO', flag: '🇩🇴', en: 'Dominican Republic', ar: 'جمهورية الدومينيكان' },
    { code: 'GT', flag: '🇬🇹', en: 'Guatemala', ar: 'غواتيمالا' },
    { code: 'HN', flag: '🇭🇳', en: 'Honduras', ar: 'هندوراس' },
    { code: 'JM', flag: '🇯🇲', en: 'Jamaica', ar: 'جامايكا' },
    { code: 'TT', flag: '🇹🇹', en: 'Trinidad and Tobago', ar: 'ترينيداد وتوباغو' },
    { code: 'HT', flag: '🇭🇹', en: 'Haiti', ar: 'هايتي' },
    { code: 'SV', flag: '🇸🇻', en: 'El Salvador', ar: 'السلفادور' },
    { code: 'NI', flag: '🇳🇮', en: 'Nicaragua', ar: 'نيكاراغوا' },
    { code: 'LK', flag: '🇱🇰', en: 'Sri Lanka', ar: 'سريلانكا' },
    { code: 'MM', flag: '🇲🇲', en: 'Myanmar', ar: 'ميانمار' },
    { code: 'KH', flag: '🇰🇭', en: 'Cambodia', ar: 'كمبوديا' },
    { code: 'NP', flag: '🇳🇵', en: 'Nepal', ar: 'نيبال' },
    { code: 'UZ', flag: '🇺🇿', en: 'Uzbekistan', ar: 'أوزبكستان' },
    { code: 'KZ', flag: '🇰🇿', en: 'Kazakhstan', ar: 'كازاخستان' },
    { code: 'GE', flag: '🇬🇪', en: 'Georgia', ar: 'جورجيا' },
    { code: 'AZ', flag: '🇦🇿', en: 'Azerbaijan', ar: 'أذربيجان' },
    { code: 'AM', flag: '🇦🇲', en: 'Armenia', ar: 'أرمينيا' },
    { code: 'UG', flag: '🇺🇬', en: 'Uganda', ar: 'أوغندا' },
    { code: 'CM', flag: '🇨🇲', en: 'Cameroon', ar: 'الكاميرون' },
    { code: 'SN', flag: '🇸🇳', en: 'Senegal', ar: 'السنغال' },
    { code: 'CI', flag: '🇨🇮', en: 'Ivory Coast', ar: 'ساحل العاج' },
    { code: 'MG', flag: '🇲🇬', en: 'Madagascar', ar: 'مدغشقر' },
    { code: 'MZ', flag: '🇲🇿', en: 'Mozambique', ar: 'موزمبيق' },
    { code: 'AO', flag: '🇦🇴', en: 'Angola', ar: 'أنغولا' },
    { code: 'TW', flag: '🇹🇼', en: 'Taiwan', ar: 'تايوان' },
    { code: 'HK', flag: '🇭🇰', en: 'Hong Kong', ar: 'هونغ كونغ' },
    { code: 'MO', flag: '🇲🇴', en: 'Macau', ar: 'ماكاو' },
    { code: 'BN', flag: '🇧🇳', en: 'Brunei', ar: 'بروناي' },
];

export const LANGUAGES = [
    { code: 'en', en: 'English', ar: 'الإنجليزية' },
    { code: 'ar', en: 'Arabic', ar: 'العربية' },
    { code: 'fr', en: 'French', ar: 'الفرنسية' },
    { code: 'de', en: 'German', ar: 'الألمانية' },
    { code: 'es', en: 'Spanish', ar: 'الإسبانية' },
    { code: 'pt', en: 'Portuguese', ar: 'البرتغالية' },
    { code: 'ru', en: 'Russian', ar: 'الروسية' },
    { code: 'zh', en: 'Chinese', ar: 'الصينية' },
    { code: 'ja', en: 'Japanese', ar: 'اليابانية' },
    { code: 'ko', en: 'Korean', ar: 'الكورية' },
    { code: 'hi', en: 'Hindi', ar: 'الهندية' },
    { code: 'tr', en: 'Turkish', ar: 'التركية' },
    { code: 'id', en: 'Indonesian', ar: 'الإندونيسية' },
    { code: 'ur', en: 'Urdu', ar: 'الأردية' },
];
