import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

const eslintConfig = [
  // ── Global ignores (replaces .eslintignore in flat config) ────────────────
  // next-env.d.ts is auto-generated by Next.js and contains triple-slash refs.
  // .next/ and convex/_generated/ are build artefacts — never lint them.
  {
    ignores: [
      "**/next-env.d.ts",
      "**/.next/**",
      "**/convex/_generated/**",
      "src/lib/engines/stubs/**",
      "public/**",
      "scratch/**",
    ],
  },

  ...compat.extends("next/core-web-vitals", "next/typescript", "plugin:jsx-a11y/recommended"),
  {
    rules: {
      // ── TypeScript: relax to warn ──────────────────────────────────────────
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "@typescript-eslint/triple-slash-reference": "off",

      // next/typescript (via @typescript-eslint/recommended) sets these to error;
      // downgrade to warn so they don't block the build.
      "@typescript-eslint/no-require-imports": "warn",
      "@typescript-eslint/no-empty-object-type": "warn",
      "@typescript-eslint/no-unsafe-function-type": "warn",
      "@typescript-eslint/no-wrapper-object-types": "warn",
      "@typescript-eslint/no-unused-expressions": "warn",
      "@typescript-eslint/no-this-alias": "warn",
      "@typescript-eslint/no-namespace": "warn",
      "@typescript-eslint/no-extra-non-null-assertion": "warn",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "warn",

      // ── React ──────────────────────────────────────────────────────────────
      "react/no-unescaped-entities": "warn",
      "react-hooks/exhaustive-deps": "warn",

      // ── Accessibility (jsx-a11y) Permanent Checks ──────────────────────────
      "jsx-a11y/alt-text": "warn",
      "jsx-a11y/aria-props": "warn",
      "jsx-a11y/aria-proptypes": "warn",
      "jsx-a11y/aria-unsupported-elements": "warn",
      "jsx-a11y/role-has-required-aria-props": "warn",
      "jsx-a11y/role-supports-aria-props": "warn",
      "jsx-a11y/no-static-element-interactions": "warn",
      "jsx-a11y/click-events-have-key-events": "warn",

      // ── Next.js ────────────────────────────────────────────────────────────
      "@next/next/no-img-element": "warn",
      "@next/next/no-html-link-for-pages": "warn",

      // ── General ────────────────────────────────────────────────────────────
      "prefer-const": "warn",
      "no-var": "warn",
    }
  },
  {
    // Relax rules in test / Cypress files – types are less strict there
    files: ["**/*.cy.tsx", "**/*.cy.ts", "**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
    }
  },
  {
    // Convex server files use process.env heavily; keep pragmatic
    files: ["convex/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
    }
  }
];

export default eslintConfig;
