$filePath = 'c:\Users\ceo\OneDrive\Desktop\projects\almstkshf.com\almstkshf.com\messages\en.json'
$goodContent = Get-Content $filePath | Select-Object -First 1417
$tail = @(
    '    "keyword_label": "Keyword",',
    '    "region_label": "Region",',
    '    "langs_label": "Languages",',
    '    "coverage_log": "Coverage Log",',
    '    "rec_high_neg": "High negative sentiment detected. Recommend activating crisis management protocols immediately.",',
    '    "rec_mod_neg": "Moderate negative coverage. Monitor closely and prepare proactive messaging.",',
    '    "rec_healthy": "Coverage sentiment is healthy. Continue current media strategy."',
    '  },',
    '  "Chatbot": {',
    '    "greeting": "How can I help you today?",',
    '    "aria_open": "Open chat",',
    '    "aria_close": "Close chat"',
    '  },',
    '  "Reports": {',
    '    "pr_title": "Press Release Coverage Report",',
    '    "deep_title": "Deep Web Risk Assessment",',
    '    "osint_title": "OSINT Technical Dossier",',
    '    "summary": "Metrics Summary",',
    '    "total_reach": "Total Reach",',
    '    "total_ave": "Ad Value (AVE)",',
    '    "article_count": "Total Articles",',
    '    "coverage_details": "Coverage Details",',
    '    "ingestion_logs": "Ingestion Activity (Last 10 Runs)",',
    '    "identified_threats": "High-Risk Identified Threats",',
    '    "investigation_target": "Investigation Target",',
    '    "technical_details": "Technical Attributes",',
    '    "entity_map": "Identified Entities & Associations",',
    '    "investigation_type": "Investigation Type",',
    '    "attribute": "Attribute",',
    '    "value": "Value",',
    '    "entity_name": "Entity Name",',
    '    "entity_type": "Type",',
    '    "relevance": "Relevance",',
    '    "generated_at": "Generated At",',
    '    "data_points": "Total Data Points",',
    '    "col_date": "Date",',
    '    "col_title": "Title",',
    '    "col_source": "Source",',
    '    "col_reach": "Reach",',
    '    "col_ave": "AVE ($)",',
    '    "col_status": "Status",',
    '    "col_time": "Timestamp",',
    '    "col_count": "Articles",',
    '    "col_sentiment": "Sentiment",',
    '    "export_pdf": "Export PDF",',
    '    "export_excel": "Export Excel",',
    '    "export_dossier": "Export Dossier"',
    '  }',
    '}'
)
$goodContent + $tail | Set-Content $filePath -Force
